apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . | quote }}
  labels:
    app: {{ include "fullname" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: "lenses"
    lenses.io/app: "{{ include "fullname" . }}"
    lenses.io/app.type: lenses
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  # Horizontal scaling is not yet supported
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "fullname" . | quote }}
  strategy:
    type: {{ default "Recreate" .Values.strategy.type | quote }}
  template:
    metadata:
      labels:
        app: {{ include "fullname" . | quote }}
        component: "lenses"
        hostPort: {{ .Values.restPort | quote }}
        containerPort: {{ .Values.restPort | quote }}
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        prometheus.io/path: "/metrics"
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      volumes:
        - name: secrets
          secret:
            secretName: {{ include "fullname" . | quote }}
            items:
              - key: security.conf
                path: security.conf
              - key: security.append.conf
                path: security.append.conf
              - key: lenses.keytab
                path: lenses.keytab
              - key: keytab
                path: keytab
              - key: client.keystore.jks
                path: client.keystore.jks
              - key: client.truststore.jks
                path: client.truststore.jks
              - key: jaas.conf
                path: jaas.conf
              - key: schema.registry.keystore.jks
                path: schema.registry.keystore.jks
              - key: schema.registry.truststore.jks
                path: schema.registry.truststore.jks
              - key: lenses.opts.keystore.jks
                path: lenses.opts.keystore.jks
              - key: lenses.opts.truststore.jks
                path: lenses.opts.truststore.jks
              {{- if .Values.lenses.tls.enabled }}
              - key: lenses.tls.keystore.jks
                path: lenses.tls.keystore.jks
              - key: lenses.tls.truststore.jks
                path: lenses.tls.truststore.jks
              {{- end }}
              # SAML Secrets
              {{- if .Values.lenses.security.saml.enabled }}
              - key: saml.keystore.jks
                path: saml.keystore.jks
              - key: saml.idp.xml
                path: saml.idp.xml
              {{- end }}
        - name: config
          configMap:
            name: {{ include "fullname" . | quote }}
        {{- if .Values.persistence.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-claim" (include "fullname" .)) }}
        {{- end }}
      serviceAccountName: {{ .Values.serviceAccount }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{if .Values.image.tag }}{{ .Values.image.tag }}{{else}}{{ .Chart.AppVersion }}{{end}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.image.registrySecretKey }}
        imagePullSecrets:
        - name: {{ .Values.image.registrySecretKey }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.restPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.restPort }}
          {{- if .Values.lenses.tls.enabled }}
            scheme: HTTPS
          {{- end }}
          initialDelaySeconds: 300
          periodSeconds: 10
        volumeMounts:
          - name: secrets
            mountPath: "/mnt/secrets"
          - name: secrets
            mountPath: "/etc/keytab"
            subPath: "keytab"
          - name: secrets
            mountPath: "/etc/registry.keytab"
            subPath: "registry.keytab"
          - name: secrets
            mountPath: "/mnt/settings/security.append.conf"
            subPath: "security.append.conf"
          - name: config
            mountPath: "/mnt/settings/lenses.append.conf"
            subPath: "lenses.append.conf"
          {{- if and .Values.lenses.kafka.sasl.enabled .Values.lenses.kafka.sasl.krb5Conf }}
          - name: config
            mountPath: "/etc/krb5.conf"
            subPath: "krb5.conf"
          {{- end }}
          {{- if .Values.persistence.enabled }}
          - name: storage
            mountPath: "/data/storage"
          {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        {{- if .Values.lenses.tls.enabled }}
        {{- if .Values.lenses.tls.keyStoreFileData }}
        - name: LENSES_SSL_KEYSTORE_LOCATION
          value: "/mnt/secrets/lenses.tls.keystore.jks"
        {{- end }}
        {{- if .Values.lenses.tls.keyStorePassword }}
        - name: LENSES_SSL_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "lenses.tls.keystore.password"
        {{- end }}
        {{- if .Values.lenses.tls.keyPassword }}
        - name: LENSES_SSL_KEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "lenses.tls.key.password"
        {{- end }}
        {{- if .Values.lenses.tls.auth }}
        - name: LENSES_SSL_CLIENT_AUTH
          value: {{ .Values.lenses.tls.auth }}
        {{- end }}
        {{- if .Values.lenses.tls.trustStoreFileData }}
        - name: LENSES_SSL_TRUSTSTORE_LOCATION
          value: "/mnt/secrets/lenses.tls.truststore.jks"
        {{- end }}
        {{- if .Values.lenses.tls.trustStorePassword }}
        - name: LENSES_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "lenses.tls.truststore.password"
        {{- end }}
        {{- end }}

        - name: LENSES_OPTS
          value: {{ .Values.lenses.lensesOpts | default "" | quote }}
        {{- if .Values.lenses.opts.keyStoreFileData }}
        - name: CLIENT_OPTS_KEYSTORE_FILE
          value: "/mnt/secrets/lenses.opts.keystore.jks"
        - name: LENSES_OPTS
          value: "$(LENSES_OPTS) -Djavax.net.ssl.keyStore=$(CLIENT_OPTS_KEYSTORE_FILE)"
        {{- end }}
        {{- if .Values.lenses.opts.keyStorePassword }}
        - name: CLIENT_OPTS_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "lenses.opts.keystore.password"
        - name: LENSES_OPTS
          value: "$(LENSES_OPTS) -Djavax.net.ssl.keyStorePassword=$(CLIENT_OPTS_KEYSTORE_PASSWORD)"
        {{- end }}
        {{- if .Values.lenses.opts.trustStoreFileData }}
        - name: CLIENT_OPTS_TRUSTSTORE_FILE
          value: "/mnt/secrets/lenses.opts.truststore.jks"
        - name: LENSES_OPTS
          value: "$(LENSES_OPTS) -Djavax.net.ssl.trustStore=$(CLIENT_OPTS_TRUSTSTORE_FILE)"
        {{- end }}
        {{- if .Values.lenses.opts.trustStorePassword }}
        - name: CLIENT_OPTS_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "lenses.opts.truststore.password"
        - name: LENSES_OPTS
          value: "$(LENSES_OPTS) -Djavax.net.ssl.trustStorePassword=$(CLIENT_OPTS_TRUSTSTORE_PASSWORD)"
        {{- end }}
        {{- if .Values.lenses.licenseUrl }}
        - name: LICENSE_URL
          value: {{ .Values.lenses.licenseUrl }}
        {{- end }}
        {{- if and .Values.lenses.kafka.sasl.jaasFileData .Values.lenses.kafka.sasl.jaasConfig }}
        {{/* Deliberately fail helm deployment if both vaues are set */}}
        {{ required "Both jaasFileData and jaasConfig are defined, pick one." nil }}
        {{- end }}
        {{- if and .Values.lenses.kafka.sasl.enabled .Values.lenses.kafka.sasl.jaasFileData }}
        - name: LENSES_OPTS
          value: "$(LENSES_OPTS) -Djava.security.auth.login.config=/mnt/secrets/jaas.conf"
        {{- end }}
        {{- if.Values.lenses.jvm.heapOpts}}
        - name: LENSES_HEAP_OPTS
          value: {{ .Values.lenses.jvm.heapOpts | quote }}
        {{- end }}
        {{- if.Values.lenses.jvm.logBackOpts}}
        - name: LENSES_LOG4J_OPTS
          value: {{ .Values.lenses.jvm.logBackOpts | quote }}
        {{- end }}
        {{- if.Values.lenses.jvm.performanceOpts}}
        - name: LENSES_PERFORMANCE_OPTS
          value: {{ .Values.lenses.jvm.performanceOpts | quote }}
        {{- end }}
        - name: LICENSE
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key: "license"
        - name: LENSES_PORT
          value: {{ .Values.restPort | quote }}
        - name: LENSES_JMX_PORT
          value: "9101"
        - name: LENSES_KAFKA_BROKERS
          value: {{ include "bootstrapBrokers" . | quote }}
        {{- if.Values.lenses.kafka.metrics.enabled }}
        - name: LENSES_KAFKA_METRICS
          value: |-
{{ include "kafkaMetrics" . | indent 12 }}
        {{- end }}
        {{- if.Values.lenses.jmxBrokers}}
        - name: LENSES_JMX_BROKERS
          value: |-
{{ include "jmxBrokers" . | indent 12 }}
        {{- end }}
        {{- if .Values.lenses.zookeepers.enabled }}
        - name: LENSES_ZOOKEEPER_HOSTS
          value: |-
{{ include "zookeepers" . | indent 12 }}
        {{- end }}

        {{- if .Values.lenses.zookeepers.chroot }}
        - name: LENSES_ZOOKEEPER_CHROOT
          value: {{ .Values.lenses.zookeepers.chroot | quote }}
        {{- end }}

        # Schema Registries
        - name: LENSES_SCHEMA_REGISTRY_URLS
          value: |-
{{ include "registries" . | indent 12 }}
        - name: LENSES_SCHEMA_REGISTRY_MODE
          value: {{ default "" .Values.lenses.schemaRegistries.mode | quote }}
        # from secrets as might contain basic auth credentials
        - name: LENSES_KAFKA_CONNECT_CLUSTERS
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key: "connect.clusters"

        - name: LENSES_ALERT_CONSUMERS_LAG_THRESHOLD
          value: {{ .Values.lenses.alerts.consumersLagThreshold | quote }}
        {{- if .Values.lenses.alerts.enabled }}
        - name: LENSES_ALERT_PLUGINS
          value: |-
{{ include "alertPlugins" . | indent 12 }}
        {{- end }}
        {{- if .Values.lenses.grafanaUrl }}
        - name: LENSES_GRAFANA
          value: {{ .Values.lenses.grafanaUrl | quote }}
        {{- end }}

        # lenses topics
        - name: LENSES_TOPICS_AUDITS
          value: {{ include "auditTopic" . | quote }}
        - name: LENSES_TOPICS_METRICS
          value: {{ include "metricTopic" . | quote }}
        - name: LENSES_TOPICS_PROFILES
          value: {{ include "profileTopic" . | quote }}
        - name: LENSES_TOPICS_PROCESSORS
          value: {{ include "processorTopic" . | quote }}
        - name: LENSES_TOPICS_CLUSTER
          value: {{ include "clusterTopic" . | quote }}
        - name: LENSES_TOPICS_ALERTS_STORAGE
          value: {{ include "alertTopic" . | quote }}
        - name: LENSES_TOPICS_ALERTS_SETTINGS
          value: {{ include "alertSettingTopic" . | quote }}
        - name: LENSES_TOPICS_LSQL_STORAGE
          value: {{ include "lsqlTopic" . | quote }}
        - name: LENSES_TOPICS_METADATA
          value: {{ include "metadataTopic" . | quote }}
        - name: LENSES_TOPICS_EXTERNAL_TOPOLOGY
          value: {{ include "topologyTopic" . | quote }}
        - name: LENSES_SCHEMA_REGISTRY_TOPICS
          value:  {{ .Values.lenses.schemaRegistries.topic | quote }}
        {{- if .Values.lenses.kafka.jmxPort }}
        - name: LENSES_JMX_BROKER_PORT
          value: {{ .Values.lenses.kafka.jmxPort | quote }}
        {{- end }}

        # Kubernetes Processors
        - name: LENSES_SQL_EXECUTION_MODE
          value: {{ .Values.lenses.sql.mode | quote }}

        # user secrets
        - name: LENSES_SECRET_FILE
          value: "/mnt/secrets/security.conf"
        - name: LENSES_SCHEMA_REGISTRY_AUTH
          value: {{ default "" .Values.lenses.schemaRegistries.security.authType | quote }}
        - name: LENSES_SCHEMA_REGISTRY_USERNAME
          value: {{ default "" .Values.lenses.schemaRegistries.security.username | quote }}
        - name: LENSES_SCHEMA_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key: "schema.registry.password"
        - name: LENSES_KAFKA_SETTINGS_CLIENT_BASIC_AUTH_CREDENTIALS_SOURCE
          value: {{ default "" .Values.lenses.schemaRegistries.security.authType | quote }}
        - name: LENSES_KAFKA_SETTINGS_CLIENT_BASIC_AUTH_USER_INFO
          value: {{ include "kafkaSchemaBasicAuth" . | quote }}

        # ssl/sasl
        {{- if .Values.lenses.jvm.trustStoreFileData }}
        - name: FILECONTENT_JVM_SSL_TRUSTSTORE
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "jvm.truststore.jks"
        {{- end }}
        {{- if .Values.lenses.jvm.trustStorePassword }}
        - name: FILECONTENT_JVM_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "jvm.truststore.password"
        {{- end }}
        - name: LENSES_KAFKA_SETTINGS_CLIENT_SECURITY_PROTOCOL
          value: {{ include "securityProtocol" . | quote }}
        - name: LENSES_KAFKA_SETTINGS_CLIENT_SASL_MECHANISM
          value: {{ default "GSSAPI" .Values.lenses.kafka.sasl.mechanism | quote }}
        {{- if and .Values.lenses.kafka.ssl.trustStoreFileData .Values.lenses.kafka.ssl.enabled }}
        - name: LENSES_KAFKA_SETTINGS_CLIENT_SSL_TRUSTSTORE_LOCATION
          value: "/mnt/secrets/client.truststore.jks"
        {{- end -}}
        {{- if and .Values.lenses.kafka.ssl.keyStoreFileData .Values.lenses.kafka.ssl.enabled }}
        - name: LENSES_KAFKA_SETTINGS_CLIENT_SSL_KEYSTORE_LOCATION
          value: "/mnt/secrets/client.keystore.jks"
        {{- end -}}
        {{- if and .Values.lenses.kafka.ssl.trustStorePassword .Values.lenses.kafka.ssl.enabled }}
        - name: LENSES_KAFKA_SETTINGS_CLIENT_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "client.truststore.password"
        {{- end -}}
        {{- if and .Values.lenses.kafka.ssl.keyStorePassword .Values.lenses.kafka.ssl.enabled }}
        - name: LENSES_KAFKA_SETTINGS_CLIENT_SSL_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "client.keystore.password"
        {{- end -}}
        {{- if and .Values.lenses.kafka.ssl.keyPassword .Values.lenses.kafka.ssl.enabled }}
        - name: LENSES_KAFKA_SETTINGS_CLIENT_SSL_KEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "client.key.password"
        {{- end }}
        {{- if .Values.lenses.schemaRegistries.ssl.trustStoreFileData }}
        - name: LENSES_SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION
          value: "/mnt/secrets/schema.registry.truststore.jks"
        {{- end -}}
        {{- if .Values.lenses.schemaRegistries.ssl.keyStoreFileData }}
        - name: LENSES_SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION
          value: "/mnt/secrets/schema.registry.keystore.jks"
        {{- end -}}
        {{- if .Values.lenses.schemaRegistries.ssl.trustStorePassword }}
        - name: LENSES_SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "schema.registry.truststore.password"
        {{- end -}}
        {{- if .Values.lenses.schemaRegistries.ssl.keyStorePassword }}
        - name: LENSES_SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "schema.registry.keystore.password"
        {{- end -}}
        {{- if .Values.lenses.schemaRegistries.ssl.keyPassword }}
        - name: LENSES_SCHEMA_REGISTRY_SSL_KEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "schema.registry.key.password"
        {{- end }}

        # Kubernetes processors
        {{- if eq .Values.lenses.sql.mode "KUBERNETES"}}
        - name: LENSES_KUBERNETES_PROCESSOR_IMAGE_NAME
          value: {{ .Values.lenses.sql.processorImage | quote }}
        - name: LENSES_KUBERNETES_PROCESSOR_IMAGE_TAG
          value: {{ .Values.lenses.sql.processorImageTag | quote }}
        - name: LENSES_KUBERNETES_POD_HEAP
          value: {{ .Values.lenses.sql.heap | quote }}
        - name: LENSES_KUBERNETES_POD_MIN_HEAP
          value: {{ .Values.lenses.sql.minHeap | quote }}
        - name: LENSES_KUBERNETES_POD_MEM_LIMIT
          value: {{ .Values.lenses.sql.memLimit | quote }}
        - name: LENSES_KUBERNETES_POD_MEM_REQUEST
          value: {{ .Values.lenses.sql.memRequest | quote }}
        - name: LENSES_KUBERNETES_POD_LIVENESS_INITIAL_DELAY
          value: {{ .Values.lenses.sql.livenessInitialDelay | quote }}
        {{- end }}

        # Deployments
        {{- if.Values.lenses.deployments.eventsBufferSize }}
        - name: LENSES_DEPLOYMENTS_EVENTS_BUFFER_SIZE
          value: {{ .Values.lenses.deployments.eventsBufferSize | quote }}
        {{- end }}
        {{- if.Values.lenses.deployments.errorsBufferSize }}
        - name: LENSES_DEPLOYMENTS_ERRORS_BUFFER_SIZE
          value: {{ .Values.lenses.deployments.errorsBufferSize | quote }}
        {{- end }}
        {{- if.Values.lenses.deployments.connect.statusInterval }}
        - name: LENSES_DEPLOYMENT_CONNECT_STATUS_INTERVAL
          value: {{ .Values.lenses.deployments.connect.statusInterval | quote }}
        {{- end }}
        {{- if.Values.lenses.deployments.connect.actionsBufferSize }}
        - name: LENSES_DEPLOYMENT_CONNECT_ACTIONS_BUFFER_SIZE
          value: {{ .Values.lenses.deployments.connect.actionsBufferSize | quote }}
        {{- end }}

        # Custom env variables
        {{- range $key, $value := .Values.lenses.env }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}

        # extras configs
        {{- range $key, $value := .Values.lenses.configOverrides }}
        - name: {{ printf "%s" $key | replace "." "_" | upper | quote }}
          value: {{ $value | quote }}
        {{- end }}

        - name: LT_PACKAGE
          value: "helm"

        - name: LT_PACKAGE_VERSION
          value: "{{ .Chart.Version }}"

      {{- if .Values.sidecarContainers }}
      {{- toYaml .Values.sidecarContainers | nindent 6 }}
      {{- end }}
